Docker
TalesMiguel/doe-se pull request #6
Opened 2022-11-24 18:13 UTC by joaop01

2022-12-05 03:10 UTC, TalesMiguel requested changes

2022-12-05 03:10 UTC, TalesMiguel commented on backend/requirements.txt
> -uWSGI==2.0.20
tenta subir sem deletar essa linha. No seu local, se não tá rolando, deixa ela comentada

acho que isso impacta prod se tirar

2022-12-05 03:10 UTC, TalesMiguel commented on nginx_conf/default.conf
> +server {
não commita esse arquivo. Isso tá sendo feito direto no servidor, posso trazer pra cá se precisarem mas não pode subir esse arquivo pra prod não

2022-12-09 13:08 UTC, Riiber0 commented on nginx_conf/default.conf
> +server {
removido

2022-12-09 21:36 UTC, merged